config/routes.rb
Huddle::Application.routes.draw do

  resource :dashboard, :only => [:show]

  resources :status_reports

  resources :projects

  devise_for :users

  namespace :api do
    resources :posts
  end

  match 'home/recentposts'
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

  match '*path(.:format)', :to => 'application#routing_error'
end

app/models/status_report.rb
class StatusReport < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  attr_accessible :invoke, :rspec, :status_date, :today, :yesterday, :project_id, :user_id

  validates :yesterday, :presence => true
  validates :today, :presence => true
  validates :project_id, :presence => true

end

app/controllers/status_reports_controller.rb
class StatusReportsController < ApplicationController
 before_filter :authenticate_user!, :only => [:new, :edit, :update, :destroy]
  # GET /status_reports
  # GET /status_reports.json
  def index
    if current_user
      @status_reports = current_user.status_reports.order("created_at DESC")
    else
      @status_reports = StatusReport.all
    end
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @status_reports }
    end
  end

  # GET /status_reports/1
  # GET /status_reports/1.json
  def show
    @status_report = StatusReport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status_report }
    end
  end

  # GET /status_reports/new
  # GET /status_reports/new.json
  def new
    @status_report = StatusReport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status_report }
    end
  end

  # GET /status_reports/1/edit
  def edit
    @status_report = StatusReport.find(params[:id])
    @projects = current_user.projects.order('name ASC')
  end

  # POST /status_reports
  # POST /status_reports.json
  def create
     
    @status_report = StatusReport.new(params[:status_report])
    @status_report.user_id = current_user.id
    @status_report.status_date = Time.zone.now.to_datetime

    respond_to do |format|
      if @status_report.save
        format.html { redirect_to @status_report, notice: 'Status report was successfully created.' }
        format.json { render json: @status_report, status: :created, location: @status_report }
      else
        format.html { render action: "new" }
        format.json { render json: @status_report.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /status_reports/1
  # PUT /status_reports/1.json
  def update
    @status_report = StatusReport.find(params[:id])

    respond_to do |format|
      if @status_report.update_attributes(params[:status_report])
        format.html { redirect_to @status_report, notice: 'Status report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_reports/1
  # DELETE /status_reports/1.json
  def destroy
    @status_report = StatusReport.find(params[:id])
    @status_report.destroy

    respond_to do |format|
      format.html { redirect_to status_reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/status_reports_helper.rb
module StatusReportsHelper
end

app/views/status_reports/_form.html.erb
<%= form_for(:status_reports) do |f| %>
 

  <div class="field">
    <%= f.label :project %><br />
    
  </div>
  <div class="field">
    <%= f.label :user %><br />
    
  </div>
  <div class="field">
    <%= f.label :yesterday %><br />
    
  </div>
  <div class="field">
    <%= f.label :today %><br />
    
  </div>
  <div class="field">
    <%= f.label :status_date %><br />
    
  </div>
  <div class="field">
    <%= f.label :invoke %><br />
    
  </div>
  <div class="field">
    <%= f.label :rspec %><br />
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/status_reports/_myposts.html.erb
<% @status_reports.each do |post| %>
	<div class="row">
		<div class="span7 well">
			<div class="span1" style="margin-left: -5px">
				<%= image_tag("#{post.user.avatar}") %>
			</div>
			<div class="span4">
				<!-- <div class="display-name">
					<%= post.user.display_name %>
				</div> -->
				<div class="project-name">
					
				</div>
<span class="">Yesterday:</span>
				<div class="yesterday">
					<%= post.yesterday %>
				</div>
<span class="">Today:</span>
				<div class="today">
					<%= post.today %>
				</div>
				<span class="light">
					posted by: <%= post.user.display_name %> /
					posted: <%= time_ago_in_words(post.created_at) %>
				</span>
			</div>
			<div class="icon" style="float: right">
				<%= post.project.name %>
			</div>

		</div>
	</div>
<% end %>

app/views/status_reports/_status_form.html.erb
<%= form_for(@status_report, :url => api_posts_path, method: :post, :remote => true) do |f| %>
<!-- 
  <div class="field">
    <%= f.label :project, :style =>"color:white" %>
    <%= f.collection_select(:project_id, Project.all, :id, :name)%>
  </div>
   -->
  <div class="field">
    <%= f.label :project, :style =>"color:white" %>
    <%= f.collection_select(:project_id, @projects, :id, :name)%>
  </div>

  <div class="field">
    <%= f.label :yesterday , :style =>"color:white" %>
    <%= f.text_area(:yesterday, :cols => 20, :rows => 5) %>
  </div>
  <div class="field">
    <%= f.label :today , :style =>"color:white" %>
    <%= f.text_area :today, :clos => 20, :rows => 5 %>
  </div>
  <!-- 
  <%= f.hidden_field(:user_id,:value => current_user.id) %>
  <%= f.hidden_field(:status_date,:value => "#{Time.zone.now.to_datetime}") %> 
  -->
  <!-- <div class="field">
    
    <%= f.label :status_date %><br />
    <%= f.date_select :status_date %>
  </div>
  -->
  <input type='hidden' id='success_function' value='post_added' />
  <div class="actions">
    <%= f.submit "Post", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/status_reports/edit.html.erb
<div class="root">
	<div class="row">
	  <div class="span12">
	    <div class="well black-transparent-box">
	        <div class="grey-box">
		        <h1>Editing status_report</h1>

				<%= render 'status_form' %>

				<%= link_to 'Show', @status_report %> |
				<%= link_to 'Back', status_reports_path %>
	        </div>
	    </div>
	  </div>
	</div>
</div>

app/views/status_reports/index.html.erb
<div class="root">
    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span8">
                    <div class="grey-box">
                        <h3>My Posts</h3>
                        <hr />
                        <div>
                            <%= render :partial => 'myposts' %>
                        </div>
                    </div>
                </div>
                <div class="span4">
                    <div class="black-transparent-box">
                        <h3>Side Span4 - 1</h3>
                        <% if current_user %>
                            <%= current_user.role %>
                        <% end %>

                    </div>
                    <br/>
                    <div class="black-transparent-box">
                        <h3>Side Span4 - 2</h3>
                        <% if current_user %>
                            <%= current_user.role %>
                        <% end %>
                        
                    </div>
                    <br/>
                    
                </div>
            </div>
            
        </div>
    </div>
</div>

app/views/status_reports/new.html.erb
<h1>New status_report</h1>

<%= render 'form' %>

<%= link_to 'Back', status_reports_path %>

app/views/status_reports/show.html.erb
<div class="root">
  <div class="row">
    <div class="span12">
      <div class="well black-transparent-box">
          <div class="grey-box">
          <p id="notice"><%= notice %></p>

          <p>
            <b>Project:</b>
            <%= @status_report.project.name %>
          </p>

          <p>
            <b>User:</b>
            <%= @status_report.user.display_name %>
          </p>

          <p>
            <b>Yesterday:</b>
            <%= @status_report.yesterday %>
          </p>

          <p>
            <b>Today:</b>
            <%= @status_report.today %>
          </p>

          <p>
            <b>Status date:</b>
            <%= @status_report.status_date %>
          </p>


          <%= link_to 'Edit', edit_status_report_path(@status_report) %> |
          <%= link_to 'Back', status_reports_path %>
          </div>
      </div>
    </div>
  </div>
</div>